name: think_flow
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.6.2 <4.0.0'

#--------------- PACKAGES ------------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.2.0
  url_launcher: ^6.2.6
  flutter_native_splash: ^2.4.0
  connectivity_plus: ^6.0.3
  lottie: ^3.1.0 # OR RIVE
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.5.2

  # Icons
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  mobx: ^2.5.0
  flutter_mobx: ^2.3.0

  # Networking & API
  dio: ^5.8.0+1
  cached_network_image: ^3.4.1
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.2.0

  # Navigation & Routing
  auto_route: ^7.8.4

  # UI & Layout
  flutter_screenutil: ^5.9.3
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1
  readmore: ^3.0.0
  capped_progress_indicator: ^0.0.2
  animation_wrappers: ^3.0.0
  shimmer: ^3.0.0
  flutter_spinkit: ^5.2.1
  flutter_speed_dial: ^7.0.0
  flutter_quill: ^11.2.0
  speech_to_text: ^7.0.0
  avatar_glow: ^3.0.1
  mind_map: ^1.0.5


  # Dependency Injection
  get_it: ^7.6.7
  flutter_sound: ^9.28.0
  just_audio: ^0.10.0
  audio_session: ^0.1.25
  permission_handler: ^12.0.0+1
  record: ^6.0.0
  path_provider: ^2.1.5
  path: ^1.9.0
  audio_waveforms: ^1.3.0
  flutter_html: ^3.0.0
  file_picker: ^10.1.2
  image_picker: ^1.1.2
  google_mlkit_text_recognition: ^0.15.0
  web_socket_channel: ^3.0.3

#--------------- ./ PACKAGES END ------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  auto_route_generator: ^7.3.2
  mobx_codegen: ^2.0.5

flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/logos/
    - assets/images/content/
    - assets/images/animations/
    - assets/icons/payment_methods/
    - assets/images/on_boarding_images/

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
