name: think_flow
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: '>=3.6.2 <4.0.0'

#--------------- DEPENDENCIES ------------------#
dependencies:
  flutter:
    sdk: flutter

  # Core & Utility
  url_launcher: ^6.2.6
  connectivity_plus: ^6.0.3
  shared_preferences: ^2.5.2
  path_provider: ^2.1.5
  path: ^1.9.0
  device_info_plus: ^9.1.2

  # State Management
  get: ^4.6.6
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0

  # Networking & API
  dio: ^5.8.0+1
  cached_network_image: ^3.4.1
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.2.0

  # Navigation & Routing
  auto_route: ^7.8.4

  # UI & Animation
  iconsax: ^0.0.8
  flutter_native_splash: ^2.4.0
  lottie: ^3.1.0
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  animation_wrappers: ^3.0.0
  flutter_spinkit: ^5.2.1
  flutter_speed_dial: ^7.0.0
  avatar_glow: ^3.0.1
  mind_map: ^1.0.5
  flutter_html: ^3.0.0
  flutter_quill: ^11.2.0

  # Media & Files
  just_audio: ^0.10.0
  record: ^6.0.0
  audio_waveforms: ^1.3.0
  file_picker: ^10.1.2
  image_picker: ^1.1.2
  ffmpeg_kit_flutter_new: ^1.4.1

  # Machine Learning
  google_mlkit_text_recognition: ^0.15.0

  # Firebase & Notifications
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^19.2.0

#--------------- DEV DEPENDENCIES ------------------#
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  auto_route_generator: ^7.3.2
  flutter_launcher_icons: ^0.14.3

#--------------- LAUNCHER ICON CONFIG ------------------#
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logos/logo_foreground.png"
  adaptive_icon_foreground: "assets/logos/logo_foreground.png"
  adaptive_icon_background: "#FFFFFF"
  remove_alpha_ios: true

#--------------- FLUTTER CONFIG ------------------#
flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/images/content/
    - assets/images/animations/
    - assets/images/on_boarding_images/
    - shorebird.yaml

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
