import 'package:audio_waveforms/audio_waveforms.dart';
import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import 'package:flutter_quill/flutter_quill.dart' show Document, QuillController, QuillEditor, QuillEditorConfig, QuillSimpleToolbar, QuillSimpleToolbarConfig;
import 'package:iconsax/iconsax.dart';
import 'package:mind_map/mind_map.dart';
import 'package:think_flow/common/widgets/empty/t_empty.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:think_flow/common/widgets/loading/loading.dart';
import 'package:just_audio/just_audio.dart';
import 'package:think_flow/presentation/screens/notes/widgets/audio_notes/widgets/audio_player_controls.dart';
import 'package:flutter_html/flutter_html.dart' as html;
import 'package:think_flow/utils/popups/loaders.dart';
import 'dart:async';
import 'dart:io';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import 'package:record/record.dart';
import 'package:avatar_glow/avatar_glow.dart';
import 'package:image_picker/image_picker.dart';

import '../../../../common/widgets/warning/t_warning_popup.dart';
import '../../../../data/models/text_note_model.dart';
import '../../../../services/text_recognizer.dart';
import '../../../../utils/constants/sizes.dart';
import '../../../../utils/constants/colors.dart';
import '../../../../utils/utils.dart';
import '../../notes/widgets/audio_notes/widgets/recording_list_item.dart';
import '../../notes/widgets/audio_notes/widgets/recording_controls.dart';
import '../bloc/note_detail_bloc.dart';
import 'package:think_flow/data/models/audio_note_model.dart';

part 'text_detail_tab/text_detail_tab.dart';
part 'audio_detail_tab/audio_detail_tab.dart';
part 'summary_detail_tab/summary_detail_tab.dart';
part 'mindmap_detail_tab/mindmap_detail_tab.dart';