// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChJB90SPVVOQrqB0tdVwxcAPfGblPFYlY',
    appId: '1:959652301982:web:6f25b26d13dcdfedfbbf8f',
    messagingSenderId: '959652301982',
    projectId: 'thinkflow-e26e1',
    authDomain: 'thinkflow-e26e1.firebaseapp.com',
    storageBucket: 'thinkflow-e26e1.firebasestorage.app',
    measurementId: 'G-S27V9MKD5Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDunCeI7V6ssieIK2WZ7HSHWa4fCkOt7eo',
    appId: '1:959652301982:android:0e88178842274a57fbbf8f',
    messagingSenderId: '959652301982',
    projectId: 'thinkflow-e26e1',
    storageBucket: 'thinkflow-e26e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy1m8aWe8Y_GaX31RsWHNJihhONq2RRfg',
    appId: '1:959652301982:ios:d410140681813acdfbbf8f',
    messagingSenderId: '959652301982',
    projectId: 'thinkflow-e26e1',
    storageBucket: 'thinkflow-e26e1.firebasestorage.app',
    iosBundleId: 'com.example.thinkFlow',
  );
}
